volumes:
  postgres_data:

services:
  postgres:
    container_name: transaction-map
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: transaction_map_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
